# -*- coding: utf-8 -*-
"""skripsilagi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q9btqeco7inxg_9W2wbvM5UicyP0vOn7
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import time

from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import (
    classification_report, confusion_matrix, accuracy_score,
    f1_score
)
from sklearn.inspection import permutation_importance
from imblearn.over_sampling import SMOTE
from collections import Counter

# Load data
df = pd.read_csv("AnemiaDataset.csv")

# Encode target
df['Decision_Class'] = df['Decision_Class'].astype(int)

# Encode gender
df['Gender'] = LabelEncoder().fit_transform(df['Gender'])

# Drop duplikat dan missing
df = df.drop_duplicates().dropna().reset_index(drop=True)

# Fitur dan target
features = ['Gender','Hb','MCH', 'MCHC', 'MCV', 'RBC', 'PCV']
X = df[features]
y = df['Decision_Class']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42)

# Normalisasi
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

smote = SMOTE(random_state=42)
X_train_final, y_train_final = smote.fit_resample(X_train_scaled, y_train)

df.info()

df.head()

df.isnull().sum()

print(df.columns)

# Cek distribusi kelas di data latih dan data uji
from collections import Counter

print("Distribusi kelas pada Data Latih:")
print(Counter(y_train))
print("Proporsi:", pd.Series(y_train).value_counts(normalize=True), "\n")

print("Distribusi kelas pada Data Uji:")
print(Counter(y_test))
print("Proporsi:", pd.Series(y_test).value_counts(normalize=True))

# Visualisasi
fig, ax = plt.subplots(1, 2, figsize=(12, 4))

sns.countplot(x=y_train, ax=ax[0])
ax[0].set_title("Distribusi Kelas - Data Latih")
ax[0].set_xlabel("Kelas")
ax[0].set_ylabel("Jumlah")

sns.countplot(x=y_test, ax=ax[1])
ax[1].set_title("Distribusi Kelas - Data Uji")
ax[1].set_xlabel("Kelas")
ax[1].set_ylabel("Jumlah")

plt.tight_layout()
plt.show()

df['Decision_Class'] = df['Decision_Class'].astype(str)
vc = df['Decision_Class'].value_counts()
labels = ['Anemia' if cls == '1' else 'No Anemia' for cls in vc.index]
colors = ['#ff9999' if cls == '1' else '#66b3ff' for cls in vc.index]
explode = [0.1 if cls == '1' else 0 for cls in vc.index]

# Visualisasi
f, ax = plt.subplots(1, 2, figsize=(18, 8))

vc.plot.pie(
    explode=explode,
    autopct='%1.1f%%',
    shadow=True,
    startangle=90,
    labels=labels,
    colors=colors,
    ax=ax[0]
)
ax[0].set_title('Had Anemia (Pie Chart)')
ax[0].set_ylabel('')

sns.countplot(
    x='Decision_Class',
    data=df,
    ax=ax[1],
    palette={'0': '#66b3ff', '1': '#ff9999'}
)
ax[1].set_title('Anemia (Count Plot)')
ax[1].set_xlabel('Decision Class')
ax[1].set_ylabel('Count')
ax[1].set_xticklabels(['No Anemia', 'Anemia'])

plt.show()

df.duplicated().sum()

df = df.drop_duplicates()
print("Jumlah data setelah drop duplicates:", len(df))

print(df['Gender'].unique())
print(df['Gender'].isnull().sum())

from collections import Counter

# ====== SEBELUM BALANCING ======
print("Distribusi kelas SEBELUM balancing:")
print(Counter(y_train))

plt.figure(figsize=(6,4))
sns.countplot(x=y_train)
plt.title("Distribusi Kelas SEBELUM Balancing")
plt.xlabel("Kelas")
plt.ylabel("Jumlah Sampel")
plt.show()

# ====== SESUDAH BALANCING (menggunakan SMOTE secara eksplisit) ======
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X_train, y_train)

print("Distribusi kelas SESUDAH balancing:")
print(Counter(y_resampled))

plt.figure(figsize=(6,4))
sns.countplot(x=y_resampled)
plt.title("Distribusi Kelas SESUDAH Balancing (SMOTE)")
plt.xlabel("Kelas")
plt.ylabel("Jumlah Sampel")
plt.show()

param_grid_rf = {
    'n_estimators': [100, 200, 300],
    'max_depth': [10, 20, 30, 40, 50],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

grid_rf = GridSearchCV(RandomForestClassifier(random_state=42), param_grid_rf,
                        cv=10, scoring='accuracy', n_jobs=-1, verbose=1)
print("\nTraining Random Forest...")
start = time.time()
grid_rf.fit(X_train_final, y_train_final)
print(f"Best RF Params: {grid_rf.best_params_}")
print(f"Best RF Accuracy (CV): {grid_rf.best_score_:.4f}")
print(f"Training time RF: {time.time() - start:.2f} sec")

param_grid_svm = [
    {
        'kernel': ['linear'],
        'C': [0.1, 1, 10]
    },
    {
        'kernel': ['rbf'],
        'C': [0.1, 1, 10],
        'gamma': [0.01, 0.1, 1]
    }
]

grid_svm = GridSearchCV(SVC(probability=True, random_state=42), param_grid_svm,
                         cv=10, scoring='accuracy', n_jobs=-1, verbose=1)
print("\nTraining SVM...")
start = time.time()
grid_svm.fit(X_train_final, y_train_final)
print(f"Best SVM Params: {grid_svm.best_params_}")
print(f"Best SVM Accuracy (CV): {grid_svm.best_score_:.4f}")
print(f"Training time SVM: {time.time() - start:.2f} sec")

# ============================
# 5. Evaluasi Model
# ============================
def evaluate_model(model, X_test, y_test, name):
    y_pred = model.predict(X_test)
    y_proba = model.predict_proba(X_test)[:,1] if hasattr(model, 'predict_proba') else model.decision_function(X_test)

    cm = confusion_matrix(y_test, y_pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
    plt.title(f'Confusion Matrix - {name}')
    plt.xlabel('Predicted')
    plt.ylabel('True')
    plt.show()

    print(f"\n=== {name} ===")
    print(classification_report(y_test, y_pred))
    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    print(f"Accuracy           : {acc:.4f}")
    print(f"F1 Score           : {f1:.4f}")

best_rf = grid_rf.best_estimator_
best_svm = grid_svm.best_estimator_

evaluate_model(best_rf, X_test_scaled, y_test, "Random Forest")
evaluate_model(best_svm, X_test_scaled, y_test, "SVM")

# ============================
# 6. Cross-validation (F1)
# ============================
print("\nCross-validation F1-Score (10-fold):")
cv_rf = cross_val_score(best_rf, X_train_final, y_train_final, cv=10, scoring='f1_macro')
print("Random Forest - F1 Macro per fold:", cv_rf)
print("Random Forest - Mean F1 Macro     :", cv_rf.mean())

cv_svm = cross_val_score(best_svm, X_train_final, y_train_final, cv=10, scoring='f1_macro')
print("SVM - F1 Macro per fold:", cv_svm)
print("SVM - Mean F1 Macro     :", cv_svm.mean())

# ============================
# 7. Feature Importance
# ============================
rf_feat_imp = pd.DataFrame({
    'Feature': features,
    'Importance': best_rf.feature_importances_
}).sort_values('Importance', ascending=False)

sns.barplot(x='Importance', y='Feature', data=rf_feat_imp)
plt.title("Feature Importance - Random Forest")
plt.tight_layout()
plt.show()

if hasattr(best_svm, 'coef_'):
    svm_feat_imp = pd.DataFrame({
        'Feature': features,
        'Importance': np.abs(best_svm.coef_[0])
    }).sort_values('Importance', ascending=False)

    sns.barplot(x='Importance', y='Feature', data=svm_feat_imp)
    plt.title("Feature Importance - SVM Linear")
    plt.tight_layout()
    plt.show()
else:
    print("SVM Non-linear → gunakan permutation importance...")
    result = permutation_importance(best_svm, X_test_scaled, y_test, n_repeats=10, random_state=42, n_jobs=-1)
    perm_imp_df = pd.DataFrame({
        'Feature': features,
        'Importance': result.importances_mean
    }).sort_values(by='Importance', ascending=False)

    sns.barplot(x='Importance', y='Feature', data=perm_imp_df)
    plt.title('Feature Importance - SVM (Permutation)')
    plt.tight_layout()
    plt.show()

# ============================
# 8. Semua Hasil GridSearch
# ============================
print("\n📊 Semua Hasil GridSearchCV - Random Forest:")
df_rf_results = pd.DataFrame(grid_rf.cv_results_)
df_rf_show = df_rf_results[['params', 'mean_test_score', 'std_test_score', 'rank_test_score']]
df_rf_show = df_rf_show.sort_values('rank_test_score')
print(df_rf_show.to_string(index=False))

print("\n📊 Semua Hasil GridSearchCV - SVM:")
df_svm_results = pd.DataFrame(grid_svm.cv_results_)
df_svm_show = df_svm_results[['params', 'mean_test_score', 'std_test_score', 'rank_test_score']]
df_svm_show = df_svm_show.sort_values('rank_test_score')
print(df_svm_show.to_string(index=False))

from sklearn.metrics import accuracy_score

y_pred_rf = best_rf.predict(X_test_scaled)
acc_rf = accuracy_score(y_test, y_pred_rf)
print(f"Akurasi Random Forest: {acc_rf:.4f}")

# Konversi data test menjadi DataFrame
X_test_df_svm = pd.DataFrame(X_test_scaled, columns=features)

# Prediksi dengan SVM
y_pred_svm = best_svm.predict(X_test_scaled)

# Probabilitas jika ada, jika tidak pakai decision_function
if hasattr(best_svm, 'predict_proba'):
    y_proba_svm = best_svm.predict_proba(X_test_scaled)[:, 1]
else:
    y_proba_svm = best_svm.decision_function(X_test_scaled)

# Gabungkan hasil
hasil_svm = X_test_df_svm.copy()
hasil_svm['Actual'] = y_test.reset_index(drop=True)
hasil_svm['Predicted_SVM'] = y_pred_svm
hasil_svm['Score_SVM'] = y_proba_svm

# Tampilkan
print("\n=== Hasil Prediksi - SVM ===")
print(hasil_svm)